ProyectoFinal/force-app/main/default/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectResource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Squad Lead</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ProjectResource__c.ProjectLineItem__r.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ProjectResource__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProyectoFinal/force-app/main/default/objects/ProjectLineItem__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipName>ProjectLineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QuantityHours__c</fullName>
        <label>QuantityHours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Role</valueSetName>
        </valueSet>
    </fields>
    <label>Project Item</label>
    <nameField>
        <displayFormat>PLI-{0000}</displayFormat>
        <label>ProjectLineItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProyectoFinal/force-app/main/default/objects/ProjectResource__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RatePerHour__c</fullName>
        <formula>$User.RatePerHour__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RatePerHour</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectResources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProjectResource</label>
    <nameField>
        <displayFormat>PR-{000}</displayFormat>
        <label>ProjectResource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProjectResources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProyectoFinal/force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>RatePerHour__c</fullName>
        <label>RatePerHour</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Role</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProyectoFinal/force-app/main/default/globalValueSets/Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Consultant</fullName>
    </customValue>
    <customValue>
        <fullName>Developer</fullName>
    </customValue>
    <customValue>
        <fullName>Administrator</fullName>
    </customValue>
    <customValue>
        <fullName>Business Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Designer</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <masterLabel>Role</masterLabel>
</GlobalValueSet>

ProyectoFinal/force-app/main/default/classes/ResourceService.cls
public class ResourceService {
    @AuraEnabled(cacheable=true)
    public static ResourceWrapper getResourcesWrapper(Id projectId,String Role){
        Project__c project = [SELECT Id, Start_Date__c,End_Date__c, (SELECT Id,QuantityHours__c FROM ProjectLineItems__r WHERE Role__c=: Role)FROM Project__c WHERE Id=:projectId];
        List<User> resourcesAvailable = getResourcesWrap(project,Role);
        system.debug('Estos son mis recursos: '+resourcesAvailable);
        ResourceWrapper resourceWrap = new ResourceWrapper(project,resourcesAvailable);
        return resourceWrap;
    }
    
   private static List <User> getResourcesWrap(Project__c project,String Role){
        Date startDate = project.Start_Date__c;
        Date endDate = project.End_Date__c;
        //List<ProjectResource__c> infoResourcesNotAvailable= [SELECT User__c,Id, Start_Date__c,End_Date__c From ProjectResource__c WHERE (Start_Date__c <:endDate AND Start_Date__c >=:startDate)  OR (Start_Date__c <:startDate AND End_Date__c >=:endDate)];
        List<ProjectResource__c> infoResourcesNotAvailable= [SELECT User__c,Id, Start_Date__c,End_Date__c From ProjectResource__c WHERE Start_Date__c <:startDate AND End_Date__c >=:endDate];
        System.debug('ProjectResource: '+ infoResourcesNotAvailable);
        Set<Id> resourcesNotAvailableId = new Set<Id>();
        for (ProjectResource__c projectResource:infoResourcesNotAvailable){
             resourcesNotAvailableId.add(projectResource.User__c);
        }
        System.debug('Id que no quiero: '+resourcesNotAvailableId);
        List<User> resourcesAvailable = [SELECT Id,Name, RatePerHour__c,Role__c FROM User WHERE Role__c =:Role AND Id NOT IN: resourcesNotAvailableId];
        System.debug(resourcesAvailable);
        return resourcesAvailable;
        system.debug(resourcesAvailable);
    }
    public class ResourceWrapper {
        @AuraEnabled
        public Project__c project;
        @AuraEnabled
        public List <User> resources;
        public ResourceWrapper(Project__c project,List <User>resources){
            this.project =project;
            this.resources = resources;
        }
        
    }
}