ProyectoFinal/force-app/main/default/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EstimatedHours__c</fullName>
        <label>Estimated Hours</label>
        <summarizedField>ProjectLineItem__c.EstimatedHours__c</summarizedField>
        <summaryForeignKey>ProjectLineItem__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ProjectResource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Squad Lead</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ProjectResource__c.ProjectLineItem__r.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ProjectResource__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProyectoFinal/force-app/main/default/objects/Project_Task__c.object
<CustomObject>
    <fields>
        <fullName>EstimatedHours__c</fullName>
        <label>Estimated Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProjectResource__c</fullName>
        <label>Project Resource</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>ProjectResource__c.ProjectLineItem__r.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ProjectResource__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <valueField>Project__c.ProjectResource__r.User__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Project Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RegisterHours__c</fullName>
        <label>Register Hours</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started yet</fullName>
                    <default>true</default>
                    <label>Not started yet</label>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProyectoFinal/force-app/main/default/objects/ProjectResource__c.object
<CustomObject>
    <fields>
        <fullName>EstimatedHours__c</fullName>
        <label>EstimatedHours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ProjectResources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProjectResource</label>
    <nameField>
        <displayFormat>PR-{000}</displayFormat>
        <label>ProjectResource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProjectResources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProyectoFinal/force-app/main/default/classes/TaskService.cls
public class TaskService {
    
    //|------Clases--------|
    public class TaskWrapper {
        @AuraEnabled
        public List <Project_Task__c> tasks;

        public TaskWrapper(List <Project_Task__c> tasks) {
            this.tasks = tasks;
        }
    }
    
    //|------Metodos--------|
    //Metodo para obtener tareas filtradas por usuario logueado *
    @AuraEnabled(cacheable=true)
    public static TaskWrapper getTasks(Id currentUser) {
        List<Project_Task__c> tasksList = [SELECT Name,State__c,EstimatedHours__c,RegisterHours__c,Project__r.Alias__c FROM Project_Task__c WHERE ProjectResource__r.User__c =:currentUser];
        return new TaskWrapper(tasksList);
    }

    //Metodo para Cambiar de estado *
    @AuraEnabled
    public static void updateTaskState(Id taskId, string state) {
        Project_Task__c task = [SELECT Id FROM Project_Task__c WHERE Id =:taskId];
        task.State__c = state;
        update task;
    }
    //Metodo para registrar horas *
    @AuraEnabled
    public static void registerHours(Id taskId, Integer hoursToAdd){
        Project_Task__c task = [SELECT Id,RegisterHours__c FROM Project_Task__c WHERE Id =:taskId];
        task.RegisterHours__c += hoursToAdd;
        update task;
    }
}